#!/usr/bin/env bash

echo "$(cat /dev/urandom | head -n2 | xxd -p | cut -c2-10 | cut -d' ' -f1)" | ssss-split -t 2 -n 2000 -w jwt | gpg --symmetric  --cipher=aes256 --always-trust --batch --armor --passphrase $1 --yes > .shamir_shares_$(date +%Y%m%d%H%M%S).dat
