#!/usr/bin/env bash
# MIT license          #
# JWT validate in bash #
########################

# jwt=$1 # pass in the jwt you want to validate in as the first argument to the script

header=$(echo -n $1 | cut -d'.' -f1)
echo $header as header
payload=$(echo -n $1 | cut -d'.' -f2)
echo $payload as payload
signature=$(echo -n $1 | cut -d'.' -f3)
echo $signature as signature

secret=${2} # pass the HMAC secret as the second argument

hexsecret=$(echo -n "$secret" | xxd -p | paste -sd "") # convert to serial hex, no pesky line breaks

mysig=$( echo -n "${header}.${payload}" | openssl dgst -sha256 -mac HMAC -macopt hexkey:$hexsecret -binary | base64 |  sed s/\+/-/g | sed 's/\//_/g' | sed -E s/=+$//)

echo "we computed $mysig"
echo "compare against signature:"

echo

if [ $mysig == $signature ]; then
  echo passed # && your API call goes here, etc
else
  echo failed # just echo out failed, or make some security API call, etc
fi
